version: '2'
services:
  nosu-rootfs:
    build: ./
    image: nosu-rootfs
    privileged: true
    volumes:
      - ".:/mnt"
    working_dir: /mnt
    command: [ "/mnt/build.sh", "/mnt/env/default" ]
    network_mode: "host"
